config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :offers do
    resources :bookings, only: %i[new create]
    resources :reviews, only: %i[new create]
  end

  resources :bookings, only: %i[index destroy]
  resources :reviews, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :offer

  # address must be provided
  validates :address, length: { minimum: 6 }
  validates :booking_date, presence: true

  validates :start_time, :end_time, presence: true
  validate :end_time_after_start_time

  private

  # start time must be before end time
  def end_time_after_start_time
    return if end_time.blank? || start_time.blank?

    if end_time < start_time
      errors.add(:end_time, 'must be after the start time')
    end
  end
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :title, :description, :category ],
    associated_against: {
      user: [ :first_name, :last_name ]
    },
    using: {
      tsearch: { prefix: true }
    }

  has_many :bookings
  # has_one_attached :photo
  has_many_attached :photos
  has_many :reviews, dependent: :destroy

  CATEGORY = ['German', 'Italian', 'Vietnamese', 'Vegan', 'French', 'Indian', 'Fusion', 'American', 'Japanese'].freeze

  # An offer must have a unique title and a description
  validates :title, uniqueness: true, presence: true
  validates :description, presence: true

  validates :price, numericality: true, presence: true
  validates :number_of_people, numericality: { only_integer: true }, presence: true
  validates :category, inclusion: { in: CATEGORY }, presence: true

  def average_rating
    if self.reviews.size > 0
      self.reviews.average(:rating)
    else
      'undefined'
    end
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :offer
  belongs_to :user
  validates :title, presence: true
  validates :content, presence: true
  validates :rating, presence: true, inclusion: [1, 2, 3, 4, 5]


end

app/models/user.rb
class User < ApplicationRecord
  has_many :offers, dependent: :destroy
  has_many :bookings
  has_one_attached :avatar_photo
  has_many :reviews

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :avatar_photo, presence: true
  # :description can be optional
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :description, :avatar_photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :description, :avatar_photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_offer
  skip_before_action :set_offer, only: %i[index destroy]
  # before_action :set_offer, only[:new , :create]

  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.offer = @offer
    if @booking.save
      # redirect_to root_path # TODO: change this link
      redirect_to dashboard_path, notice: 'Your booking was successful!'
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to dashboard_path
  end

  private

  def set_offer
    @offer = Offer.find(params[:offer_id])
  end

  def booking_params
    params.require(:booking).permit(:comment, :address, :status, :booking_date, :start_time, :end_time)
  end

  # t.text "comment"
  #   t.string "address"
  #   t.string "status"
  #   t.date "booking_date"
  #   t.time "start_time"
  #   t.time "end_time"
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  before_action :set_offer, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: %i[index show]
  def index
    if params[:query].present?
      @offers = Offer.global_search(params[:query])
    else
      @offers = Offer.all
    end
  end

  def show
    # @offer = Offer.find(params[:id])
    @review = Review.new # Added because partial review form needs it.
  end

  def new
    @offer = Offer.new
  end

  def edit
   # @offer = Offer.find(params[:id])
  end

  def create
    @offer = Offer.new(offer_params)
    @user = current_user
    @offer.user = @user
    if @offer.save
      redirect_to @offer, notice: 'Offer was successfully created.'
    else
      render :new
    end
  end

  def update
    if @offer.update(offer_params)
      redirect_to @offer, notice: 'Offer was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    # @offer = Offer.find(params[:id])
    @offer.destroy
    redirect_to dashboard_path, notice: 'Offer was successfully destroyed.'
  end

  private

  def offer_params
    params.require(:offer).permit(:title, :description, :price, :number_of_people, :category, photos: [])
  end

  def set_offer
    @offer = Offer.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end

  def dashboard
    @bookings = Booking.where(user: current_user)
    @offers = Offer.where(user: current_user)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_offer, only: %i[new create]

  # Not needed since review form is rendered in offer show page
  # view file deleted too
  # def new
  #   @review = Review.new
  # end

  def create
    @review = Review.new(review_params)
    @review.offer = @offer
    @review.user = current_user

    # Is the request of page asking for specifc format - e.g. HTML if JS is disabled?
    respond_to do |format|
      if @review.save
        # if it asks for an HTML, it will look for html.erb with same name
        # we give back regular response specifically telling to redirect
        format.html { redirect_to offer_path(@offer, anchor: "review-#{@review.id}") }
        format.json # normal Rails flow will look for a file called "create.json"
      else
        format.html { render "offers/show" }
        format.json # normal Rails flow will look for a file called "create.json"
      end
    end


  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to offer_path(@review.offer)
  end

  private

  def find_offer
    @offer = Offer.find(params[:offer_id])
  end

  def review_params
    params.require(:review).permit(:title, :content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">
  <div class="row text-center">
    <h1>My Bookings</h1>
  </div>
</div>

<div class="d-flex flex-column align-items-center">
  <div class="col-12 col-md-10 col-lg-7">
    <% @bookings.each do |booking| %>
      <%= render "shared/booking_card", booking: booking %>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-9 col-lg-6 m-3 pb-3">
      <%= render "shared/offer_card", offer: @offer %>

    <div id="new_booking" class="mt-3">
      <%= simple_form_for [@offer, @booking] do |f|%>
        <%# <%= f.input :booking_date, as: :date, html5: true %>
        <%= f.input :booking_date, as: :string, placeholder: 'Select a date',
            input_html: { data:
            { controller: "flatpickr",
              attributes: {
                dateFormat: "d.m.Y",
                minDate: Time.zone.now
              }} } %>
        <div class="d-flex" id="time-input">
          <div style="flex-grow:1">
            <%= f.input :start_time, as: :time, html5: true, placeholder: 'Please choose a time',
            input_html: { data:
            {controller: "flatpickr",
              attributes: {
                enableTime: true,
                noCalendar: true,
                dateFormat: "h:i K",
                minTime: "9:00",
                maxTime: "23:00",
                minDate: Time.zone.now
              }} }%>
          </div>
          <div style="flex-grow:1">
            <%= f.input :end_time, as: :time, html5: true, placeholder: 'Please choose a time',
            input_html: { data:
            {controller: "flatpickr",
              attributes: {
                enableTime: true,
                noCalendar: true,
                dateFormat: "h:i K",
                minTime: "9:00",
                maxTime: "23:00",
                minDate: Time.zone.now
              }} }%>
          </div>
        </div>
        <%= f.input :address, required: true %>
        <%= f.input :comment, placeholder: 'Add a message or instructions for the chef'%>
        <div class="text-center">
          <%= f.submit 'Book', class: 'btn btn-flat' %>
        </div>
      <% end %>
    </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CHEFTOGO</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag asset_path('Chef2Go.png') %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="wrapper">

      <!-- Devise alerts ad notices -->
      <%= render 'shared/flashes' %>

      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/offers/_form.html.erb
<%= simple_form_for [@offer] do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :price, as: :integer %>
  <%= f.input :number_of_people, as: :integer %>
  <%= f.input :category, collection: Offer::CATEGORY %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <div class="text-center">
    <%= f.button :submit, class: 'btn btn-flat' %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-9 m-3 pb-3">
      <h1>Editing the offer</h1>

      <%= render 'form', offer: @offer %>

      <%# <%= link_to 'Show', @offer %>
      <div class="text-center mt-2"><%= link_to 'Back', root_path %></div>
      </div>
  </div>
</div>

app/views/offers/index.html.erb
<div class="d-flex flex-column justify-content-center offers-banner" style="background-image: url(https://cdn.pixabay.com/photo/2016/12/26/17/28/spaghetti-1932466__340.jpg)">
  <div class="row text-center">
    <h1>Choose your culinary adventure!</h1>
  </div>
</div>

<div class="d-flex flex-column align-items-center">
  <div class="col-12 col-md-10 col-lg-7">
    <% @offers.each do |offer| %>
      <%= render "shared/offer_card", offer: offer %>
    <% end %>
  </div>
</div>

app/views/offers/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-9 m-3 pb-3">
      <h1>Create your new offer </h1>

      <%= render 'form', offer: @offer %>
      <div class="text-center mt-2"><%= link_to 'Cancel', offers_path%></div>
      <%# link_to 'Cancel', :back %>
    </div>
  </div>
</div>

app/views/offers/show.html.erb
<!--
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @offer.photos.first.key, crop: :fill %>')" >
  <div class="container offer-details">
    <h1><%= @offer.title %></h1>
    <p><%= @offer.description %></p>
    <%= link_to 'Book now', new_offer_booking_path(@offer), class: 'btn btn-flat' %>

    <span class='person-tag'><%= pluralize(@offer.number_of_people, 'person') %></span>
    <span class='category-tag'><%= @offer.category %></span>
    <span class='price-tag'><%= @offer.price.round %> EUR</span>
  </div>
</div>
-->
<div class="container col-10 offer-details" >
  <div class="row justify-content-between  mt-5">
    <div class="col-7">
      <h1><%= @offer.title %></h1>
      <p>
        <%= @offer.description.gsub(/(\.|!).*/, '') %> ...
        <em><%=link_to '(more info)', '#description-text' %></em>
      </p>

    </div>
    <div class="col-2 text-end">
      <p>
        Average Rating: <br>
        <% if @offer.reviews.count == 0 %>
          <% if @offer.user == current_user %>
            <small>No ratings yet!</small>
          <% else %>
            <em><%= link_to 'Rate this chef!', '#new-review' %></em>
          <% end %>
        <% end %>
        <% @offer.average_rating.to_i.times do  %>
            ⭐
        <% end %>
    </div>
  </div>
  <div class="row align-items-center">
      <div class="col">
        <span class='person-tag'><%= pluralize(@offer.number_of_people, 'person') %></span>
        <span class='category-tag'><%= @offer.category %></span>
        <span class='price-tag'><%= sprintf('%.0f', @offer.price) %> EUR</span>
      </div>
      <div class="col-6 text-end">
        <% if @offer.user == current_user %>
          <%= link_to "Edit offer", edit_offer_path, class: "btn btn-outline-secondary btn-sm" %>

          <%= link_to "Delete offer",
                      offer_path(@offer), class: "btn btn-outline-secondary btn-sm",
                      method: :delete,
                      data: { confirm: "Are you sure?" }, remote: true %>

        <% else %>
          <%= link_to 'Book now', new_offer_booking_path(@offer), class: 'btn btn-flat' %>
        <%end%>

      </div>
  </div>

  <hr>
    <% if @offer.photos.count == 1 %>
      <%= render 'shared/photos_grid_one_photo' %>
    <% else %>
      <%= render 'shared/photos_grid_first_two' %>
    <% end %>
  <hr>

  <!-- Sub-Headline description & chef -->
  <div class="row align-items-center">
    <div class="col">
      <h3>All you need to know about your experience</h3>
    </div>
    <div class="col-2 text-end">
      <%= cl_image_tag @offer.user.avatar_photo.key, class: "avatar-large", zoom: 0.7, aspect_ratio: 1, crop: :crop, gravity: :face %>
    </div>
  </div>

  <hr>
  <!-- Detailed description & reviews -->
  <div class="row" >
    <div data-controller="insert-in-list">
      <div class="col" >
        <span class="anchor" id="description-text"></span>
        <h5>Details for <%= @offer.title %> </h5>
        <p><%= truncate(@offer.description, :length => 450, :omission => '.') %></p>
      <hr>
        <h5>Read what others wrote about <%= @offer.user.first_name %>!</h5>

        <% if @offer.reviews.count == 0 %>
          <p>There are currently no reviews</p>
        <% end %>

          <%= render 'shared/review_box', offer: @offer %>

      <hr>


      </div>
      <div class="col-3">
        <span class="anchor" id="new-review"></span>
        <div >
            <h5>Leave a review for <%= @offer.title %></h5>
            <%= render "reviews/form", offer: @offer, review: @review %>
        </div>
      </div>
    </div>

  </div>

  <div class="row justify-content-center text-center">
    <hr  class="mb-3 mt-3">
    <div class="col-8 image-slider">

      <h5>See all photos here!</h5>
      <%= render 'shared/image_slider' %>

    </div>

  <!-- Layout not quite right - Slider instead.
          <% if @offer.photos.count == 1 %>
            <%= render 'shared/photos_grid_one_photo' %>
          <% else %>
            <%= render 'shared/photos_grid_all' %>
          <% end %>
  -->
  </div>




</div>

  <%# <% @article.photos.each do |photo| %>
    <%# <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
  <%# <% end %>

app/views/pages/dashboard.html.erb
<div class="container outer-container">
  <div class="row d-flex justify-content-center align-items-top">
    <div class="col-12 col-lg-5 col-xl-4 profile">
      <%= cl_image_tag current_user.avatar_photo.key, class: "avatar-xl", aspect_ratio: 1, crop: :crop, gravity: :face %>
      <h3><%= current_user.first_name.capitalize %> <%= current_user.last_name.capitalize%></h3>
      <div class="d-flex align-items-center justify-content-center text-center user-info">
        <p><%= current_user.description %></p>
      </div>
      <button class="btn profile-edit-btn">Edit Profile</button>
    </div>
    <div class="col-12 col-lg-6 tabs" data-controller="switch-tabs">
      <div class="button-container">
        <button disabled
          class="btn tab-btn"
          data-action="click->switch-tabs#toggle"
          data-switch-tabs-target="bookings">
          My Bookings
        </button>
        <% unless @offers.empty? %>
          <button
            class="btn tab-btn"
            data-action="click->switch-tabs#toggle"
            data-switch-tabs-target="offers">
            My Offers
          </button>
        <% end %>
      </div>
      <div class="d-flex flex-column align-items-center tab-content-container">
        <div class="bookings-container"
            data-action="switch-tabs#toggle"
            data-switch-tabs-target="bookingsList">
          <% if @bookings.empty? %>
          <%= render "shared/warning_card" %>
          <% else %>
            <% @bookings.each do |booking| %>
              <%= render "shared/booking_card", booking: booking %>
            <% end %>
          <% end %>
        </div>
        <div class="d-none offers-container"
            data-action="switch-tabs#toggle"
            data-switch-tabs-target="offersList">
          <% @offers.each do |offer| %>
            <%= render "shared/offer_card", offer: offer, id: "offer-card" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner homepage-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/mM-L0yx5LcQ); height:500px;">
  <div class="container text-center">
    <h1>Hire a Private Chef </h1>
    <p>Enjoy a customized culinary experience with a Private Chef in the comfort of your own home</p>
    <%= link_to 'Get Started', offers_path, class: 'btn btn-flat btn-lg' %>
  </div>
</div>
<%# <%= cl_image_tag("iaischz7fohjap0v9rvq.jpg",  width: 1400, height: 300, crop: :fill) %>
<div class="container mt-5" id="homepage-intro">
  <div class="row text-center align-items-center">
    <div class="col-12 col-md-6 homepage-intro-img">
      <%= image_tag "cook1.jpg" %>
    </div>
    <div class="col-12 col-md-6 homepage-intro-text">
      <h3>The Cooking</h3>
      <p>Your Private Chef will arrive with all the ingredients needed to prepare your dreamed meal.</p>
    </div>
  </div>
  <div class="row text-center align-items-center">
    <div class="col-12 col-md-6 homepage-intro-text">
      <h3>The Experience</h3>
      <p>Your chef will take care of your party all-throughout the experience. That means host dutties are off the table for you!</p>
    </div>
    <div class="col-12 col-md-6 homepage-intro-img">
      <%= image_tag "serve1.jpg" %>
    </div>
  </div>

  <div class="row text-center align-items-center">
    <div class="col-12 col-md-6 homepage-intro-img">
      <%= image_tag "finish.jpg" %>
    </div>
    <div class="col-12 col-md-6 homepage-intro-text">
      <h3>The Clean up</h3>
      <p> By the end of the night, all there will be left for you to do is relax and enjoy your company.</p>
    </div>
  </div>
</div>

app/views/reviews/_form.html.erb
<!-- app/views/reviews/new.html.erb -->
<%= simple_form_for([offer, review], data: { insert_in_list_target: 'form', action: 'submit->insert-in-list#send' }) do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.input :rating, as: :integer %>
  <%= f.submit "Submit review", class: "btn btn-dark" %>
<% end %>

app/views/shared/_booking_card.html.erb
<%= link_to offer_path(booking.offer) do %>
  <div class="container card-category" style="background-image: linear-gradient(rgba(243,243,243,0.8), rgba(243,243,243,0.9)), url(<%= cl_image_path booking.offer.photos.first.key %>);">

    <div class="d-flex flex-column justify-content-around card-infos">
      <h2><%= booking.offer.title %></h2><br>
      <div class="d-flex justify-content-between">
        <p><%= booking.start_time.to_s.slice(11..15) %> | <%= booking.booking_date %></p>
        <p>with: <strong><%= booking.offer.user.first_name %></strong></p>
      </div>
      <div class="d-flex justify-content-between">
        <p><%= booking.address %></p>

        <%= link_to "Cancel",
             booking_path(booking), class: "btn btn-transparent",
             method: :delete,
             data: { confirm: "Are you sure you want to cancel this booking?" } %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer mt-5">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Cooked with <i class="fas fa-heart"></i>
  </div>
</div>

app/views/shared/_image_slider.html.erb
  <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <% @offer.photos.each_with_index do |photo, index| %>
        <% if index == 0 %>
          <% style="carousel-item active"%>
        <% else %>
          <% style="carousel-item"%>
        <% end %>
        <div class="<%=style%>">
          <%= cl_image_tag photo.key, crop: :fit, class:"d-block w-100" %>
        </div>
      <% end %>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark bg-dark bg-gradient navbar-lewagon">
  <div class="container-fluid">
    <%= link_to offers_path, class: "navbar-brand" do %>
      <%= image_tag "Chef2Go.png", class: "avatar" %>
    <% end %>

    <%# <form class="d-flex align-items-center flex-nowrap" action="/offers" method="get"> %>

    <form class="d-flex" action="/offers" method="get">
      <input class="form-control me-2" id="searchbar" name ="query" type="search" placeholder="Find a culinary experience" aria-label="Search">

      <button class="btn btn-outline-secondary" type="submit">Search</button>
    </form>
  <%# </form>    %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
          <%# <% if current_user.offers.length == 0 %>
            <%= link_to "New Offer", new_offer_path, class: "nav-link" %>
          <%# <% else %>
             <%# <%= link_to "My Offers", "#", class: "nav-link" %>
          <%# <% end %>
          </li>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= cl_image_tag current_user.avatar_photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Profile", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_offer_card.html.erb
<%= link_to offer_path(offer) do %>
  <div class="container card-product">

    <%# display 1st Image %>
    <% if offer.photos.attached? %>
      <%= cl_image_tag offer.photos.first.key %>
    <% end %>

    <div class="d-flex flex-column justify-content-between card-product-infos">
      <h3><%= offer.title %></h3>
      <p><%= offer.description.gsub(/(\.|!).*/, '') %>.</p>
      <div class="d-flex justify-content-between">
        <p><b><%= offer.number_of_people %> people</b></p>
        <p><b><%= sprintf('%.0f', offer.price) %> EUR </b></p>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_photos_grid_all.html.erb
  <div class="grid-border">
    <div class="photo-grid-all">
      <% @offer.photos.each do |photo| %>
        <%= cl_image_tag photo.key, crop: :fit, class:"d-block w-100" %>
      <% end %>
    </div>
  </div>

app/views/shared/_photos_grid_first_two.html.erb
  <div class="grid-border">
    <div class="photo-grid-first-two">
      <% @offer.photos.first(2).each do |photo| %>
        <%= cl_image_tag photo.key, crop: :fit, class:"d-block w-100" %>
      <% end %>
    </div>
  </div>

app/views/shared/_photos_grid_one_photo.html.erb
  <div class="grid-border">
    <div class="photo-grid-one-photo">
      <%= cl_image_tag @offer.photos.first.key, crop: :pad, height: "400"%>
    </div>
  </div>

app/views/shared/_review_box.html.erb
<div class="review-container" >
  <ul data-insert-in-list-target="items">
    <% offer.reviews.each do |review| %>
      <div class="review-card">
        <li id="review-<%="#{review.id + 1}"%>">
          <span class="anchor"></span>
          <%= review.title %> |
          <% review.rating.to_i.times do  %>
            ⭐
          <% end %> |

          <em>
            by <%= review.user.first_name %>
            <%= link_to "(Remove review)",
                      review_path(review),
                      method: :delete,
                      data: { confirm: "Are you sure?" } %>
          </em>
        </li>

        <li>
          "<%= review.content %>"
        </li>
      </div>
    <% end %>
  </ul>
</div>

app/views/shared/_warning_card.html.erb
<div class="d-flex justify-content-center align-items-center text-container">
  <h4 class="text-center">No bookings to show yet.</h4>
</div>